# Cada linha de código abaixo, é uma configuração da ferramenta que você deseja adicionar, neste caso só há uma aplicação do NodeJS.

FROM node:16-alpine
WORKDIR /app
COPY package* .json /app/
RUN npm install
COPY . /app/
EXPOSE 3000
CMD ["npm", "start"]